### ISSUE TITLE
Needs a control for transparency/opacity.

### ISSUE THREAD

**Issue by GeneralAwareness** [Zuntan03/LatentCoupleHelper#2]
I tried to manually change it but regardless what I set the opacity to I was ignored.

**Comment by Zuntan03** [comment]
Please edit formOpacity in LatentCoupleHelper.json

**Comment by GeneralAwareness** [comment]
As I said, it did nothing (which is the manual change I attempted).  0.1 all the way to 1.0 it remained the same.

**Comment by Zuntan03** [comment]
You need to rewrite LatentCoupleHelper.json instead of LatentCoupleHelper.ps1.

If that does not work, try deleting the following lines.
LatentCoupleHelper.ps1:65
$frm.Opacity = $cfg.formOpacity;

**Comment by GeneralAwareness** [comment]
I never found the above, but I was changing this:  
![image](https://user-images.githubusercontent.com/124339252/222881958-efef75c9-a100-4500-9384-691922b4dc57.png)
in the .ps1 file when I needed to change the json.  Changing the json worked though I do not understand why the need to save that file out each time I close the program?

**Comment by Zuntan03** [comment]
That code will be the initial value if the JSON configuration file does not exist.
The user can customise it in the JSON file and if there is any trouble, it can be reset by deleting the JSON file.

**Comment by GeneralAwareness** [comment]
Yep.  The entire json stuff is new to me, but I guess it is like the old .cfg config files.
