### ISSUE TITLE
not working ;-(

### ISSUE THREAD

**Issue by Tobe2d** [Zuntan03/LatentCoupleHelper#3]
When I open "LatentCoupleHelper.bat" it open and close immediately.
Any idea how to fix this?
I am on latest Windows 11 Pro

**Comment by Zuntan03** [comment]
If you add the word pause to the last line of the bat file and run it, you may see an error.

**Comment by Zuntan03** [comment]
LatentCoupleHelper.bat
```
@echo off
PowerShell -Version 5.1 -ExecutionPolicy Bypass -File "%~dp0LatentCoupleHelper.ps1"
pause
```

**Comment by Tobe2d** [comment]
'PowerShell' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by Zuntan03** [comment]
Powershell should be available by default in Windows 11, but it does not seem to be available in your environment.

If the problem of Powershell not being available in your environment can be resolved, it may become available.

**Comment by Tobe2d** [comment]
Yes.. I added in Environment Variables "C:\Windows\System32\WindowsPowerShell\v1.0" and now it is working ;-)

Thank you!!
